[tool.poetry]
name = "pyrandomwiki"
version = "0.1.0"
description = "Python Random Wiki"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/jprimero/pyrandomwiki"
repository = "https://github.com/jprimero/pyrandomwiki"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
